[package]
authors = ["Sturdy <sturdy@apollo.farm>"]
edition = "2021"
name = "cw-dex-router"
version = "0.1.0"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = true
panic = 'abort'
rpath = false

[features]
default = ["osmosis"]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []
osmosis = ["cw-dex/osmosis"]
astroport = ["cw-dex/astroport"]

[package.metadata.scripts]
optimize = """docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/rust-optimizer:0.12.6
"""
optimize-arm64 = """docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/rust-optimizer-arm64:0.12.8
"""

[dependencies]
cosmwasm-std = "1.1"
cosmwasm-schema = "1.1"
cw-asset = { git="https://github.com/apollodao/cw-asset.git" }
cw-controllers = "0.16"
cw-dex = {git = "https://github.com/apollodao/cw-dex", branch = "develop" }
cw-storage-plus = "0.16"
cw2 = "0.16"
cw20 = "0.16"
thiserror = {version = "1.0.31"}

[dev-dependencies]
apollo-proto-rust = {git = "https://github.com/apollodao/apollo-proto-rust", tag = "v0.3.0"}
cw-multi-test = "0.16"
osmo-bindings = "0.5.1"
testcontainers = { version = "0.14.0" , features = ["experimental"] }
test-case = "2.2.2"
cw-it = { git = "https://github.com/apollodao/cw-it.git" }
osmosis-testing = { git = "https://github.com/apollodao/osmosis-rust" }
